/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import general.DatosComunes;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mantenimientos.MantenimientoIndiceBancos;
import mantenimientos.MantenimientoIndiceSucursales;

/**
 *
 * @author Txus
 */
public class TestMantenimientoIndiceBancosSucursales extends javax.swing.JFrame {

    
    MantenimientoIndiceBancos mib = null;
    MantenimientoIndiceSucursales mis = null;
    /**
     * Creates new form TestMantenimientoIndiceBancosSucursales
     */
    public TestMantenimientoIndiceBancosSucursales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbMantIndiceBancos = new javax.swing.JButton();
        jbMantIndiceSucursales = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbMantIndiceBancos.setText("Mantenimiento Indice de Bancos");
        jbMantIndiceBancos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMantIndiceBancosActionPerformed(evt);
            }
        });

        jbMantIndiceSucursales.setText("Mantenimiento Indice de Sucursales");
        jbMantIndiceSucursales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMantIndiceSucursalesActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbMantIndiceSucursales)
                    .addComponent(jbMantIndiceBancos)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbSalir)
                        .addGap(78, 78, 78)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jbMantIndiceBancos)
                .addGap(51, 51, 51)
                .addComponent(jbMantIndiceSucursales)
                .addGap(61, 61, 61)
                .addComponent(jbSalir)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
    
        System.exit(0);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbMantIndiceBancosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMantIndiceBancosActionPerformed
        
        if(mib == null){
            mib = new MantenimientoIndiceBancos(new javax.swing.JFrame(), true);
        }else{
            mib.setVisible(true);
        }
    }//GEN-LAST:event_jbMantIndiceBancosActionPerformed

    private void jbMantIndiceSucursalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMantIndiceSucursalesActionPerformed
        
        if(mis == null){
            mis = new MantenimientoIndiceSucursales(new javax.swing.JFrame(), true);
        }else{
            mis.setVisible(true);
        }
    }//GEN-LAST:event_jbMantIndiceSucursalesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new DatosComunes("MV");

        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    try {
                        UIManager.setLookAndFeel(info.getClassName());
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(TestMantenimentoFacturasEmitidas.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                        Logger.getLogger(TestMantenimentoFacturasEmitidas.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                        Logger.getLogger(TestMantenimentoFacturasEmitidas.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;
                }
            }
            /*
             try {
             UIManager.setLookAndFeel("org.jvnet.substance.skin.Substance" + "Sahara" + "LookAndFeel");
             } catch (ClassNotFoundException ex) {
             Logger.getLogger(TestMantenimientoPrevisionesCobro.class.getName()).log(Level.SEVERE, null, ex);
             } catch (InstantiationException ex) {
             Logger.getLogger(TestMantenimientoPrevisionesCobro.class.getName()).log(Level.SEVERE, null, ex);
             } catch (IllegalAccessException ex) {
             Logger.getLogger(TestMantenimientoPrevisionesCobro.class.getName()).log(Level.SEVERE, null, ex);
             }*/
        } catch (UnsupportedLookAndFeelException e) {
            System.out.println(e);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestMantenimientoIndiceBancosSucursales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbMantIndiceBancos;
    private javax.swing.JButton jbMantIndiceSucursales;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables
}
