/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimientos;

import general.DatosComunes;
import general.MysqlConnect;
import indices.IndicePrevisionesCobro;
import java.sql.ResultSet;
import javax.swing.JFrame;
import tablas.Cuenta;
import tablas.EfectoCobrar;
import tablas.Representante;
import util.Apariencia;
import util.BaseDatos;
import util.JTextFieldFecha;

/**
 *
 * @author Txus
 */
public class MantenimientoPrevisionesCobro extends util.EscapeDialog {
    // Con esta variable definimos si estamos en una consulta (TRUE) o en
    // un mantenimiento (FALSE). Nos servirá para tener un sólo programa
    // para algunas Consultas/Mantenimientos que pueden compartir las 
    // mismas pantallas.

    private static boolean consulta;
    private static boolean enCreacion = false;

    public static ResultSet rs = null;
    public static MysqlConnect m = null;
   
    private static EfectoCobrar efectoCobrar = new EfectoCobrar();
    
    IndicePrevisionesCobro indicePrevisionesCobro = null;

    // Definiciones de componentes de pantalla
    public JFrame frameMenu = null;
        
   
    /**
     * Creates new form MantenimientoPrevisionesCobro
     */
    public MantenimientoPrevisionesCobro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();        
    }
    
    public MantenimientoPrevisionesCobro(JFrame parentFrame) {
        super();
        frameMenu = parentFrame;
        initComponents();
        borrarPantalla();
        cargaInicial();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVencimiento = new javax.swing.JLabel();
        jbBuscarFechaVencimiento = new javax.swing.JButton();
        jlEfecto = new javax.swing.JLabel();
        jtfnfEfecto = new util.JTextFieldNumeroFijo(4);
        jlSituacion = new javax.swing.JLabel();
        jcbxSituacion = new javax.swing.JComboBox();
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(3);
        jPanelDatosPrevision = new javax.swing.JPanel();
        jlCliente = new javax.swing.JLabel();
        jbBuscarCliente = new javax.swing.JButton();
        jtfnfCliente = new util.JTextFieldNumeroFijo(7);
        jlFactura = new javax.swing.JLabel();
        jtfnfFactura = new util.JTextFieldNumeroFijo(6);
        jlFechaFactura = new javax.swing.JLabel();
        jlImporte = new javax.swing.JLabel();
        jtfnf2dImporte = new util.JTextFieldNumero2Decimales();
        jlBancoNegociacion = new javax.swing.JLabel();
        jbBuscarBancoNegociacion = new javax.swing.JButton();
        jtfnfBancoNegociacion = new util.JTextFieldNumeroFijo(4);
        jlFechaRemesa = new javax.swing.JLabel();
        jlRemesaDia = new javax.swing.JLabel();
        jtfnfRemesaDia = new util.JTextFieldNumeroFijo(2);
        jlRepresentante = new javax.swing.JLabel();
        jbBuscarRepresentante = new javax.swing.JButton();
        jtfnfRepresentante = new util.JTextFieldNumeroFijo(4);
        jPanelDatosDomiciliacion = new javax.swing.JPanel();
        jlBancoDomiciliacion = new javax.swing.JLabel();
        jtfnfBancoDomiciliacion = new util.JTextFieldNumeroFijo(4);
        jbBuscarBancoDomiciliacion = new javax.swing.JButton();
        jlSucursalDomiciliacion = new javax.swing.JLabel();
        jbBuscarSucursalDomiciliacion = new javax.swing.JButton();
        jtfnfSucursalDomiciliacion = new javax.swing.JTextField();
        jtfnfDigitosControl = new util.JTextFieldNumeroFijo(2);
        jlDigitosControl = new javax.swing.JLabel();
        jtfnfCuentaDomicilacion = new util.JTextFieldNumeroFijo(10);
        jlCuentaDomiciliacion = new javax.swing.JLabel();
        jlFechaCobro = new javax.swing.JLabel();
        jcbReciboEmitido = new javax.swing.JCheckBox();
        jlNombreCliente = new javax.swing.JLabel();
        jlNombreRepresentante = new javax.swing.JLabel();
        jtffFechaFactura = new util.JTextFieldFecha();
        jtffFechaRemesa = new util.JTextFieldFecha();
        jtffFechaCobro = new util.JTextFieldFecha();
        jbSalir = new javax.swing.JButton();
        jbDeduccionAbonos = new javax.swing.JButton();
        jbDepuracionRiesgo = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbGrabar = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jtffVencimiento = new util.JTextFieldFecha();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Previsiones de Cobro");

        jlVencimiento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlVencimiento.setText("Vencimiento");

        jbBuscarFechaVencimiento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarFechaVencimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarFechaVencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarFechaVencimientoActionPerformed(evt);
            }
        });

        jlEfecto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlEfecto.setText("Efecto");

        jtfnfEfecto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfEfecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnfEfectoActionPerformed(evt);
            }
        });

        jlSituacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlSituacion.setText("Situación");

        jcbxSituacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jcbxSituacion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recibo", "Negociable", "Liberado", "Remesado", "Aceptado", "Cobrado" }));

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jPanelDatosPrevision.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Previsión", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N
        jPanelDatosPrevision.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCliente.setText("Cliente");

        jbBuscarCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N

        jtfnfCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFactura.setText("Factura");

        jtfnfFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlFechaFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFechaFactura.setText("Fecha Factura");

        jlImporte.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlImporte.setText("Importe");

        jtfnf2dImporte.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlBancoNegociacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlBancoNegociacion.setText("Banco Negoc.");

        jbBuscarBancoNegociacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarBancoNegociacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N

        jtfnfBancoNegociacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlFechaRemesa.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFechaRemesa.setText("Fecha Remesa");

        jlRemesaDia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlRemesaDia.setText("Remesa Dia");

        jtfnfRemesaDia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlRepresentante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlRepresentante.setText("Representante");

        jbBuscarRepresentante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarRepresentante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarRepresentante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarRepresentanteActionPerformed(evt);
            }
        });

        jtfnfRepresentante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jPanelDatosDomiciliacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Domiciliación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        jlBancoDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlBancoDomiciliacion.setText("Banco");

        jtfnfBancoDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jbBuscarBancoDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarBancoDomiciliacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N

        jlSucursalDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlSucursalDomiciliacion.setText("Sucursal");

        jbBuscarSucursalDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscarSucursalDomiciliacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N

        jtfnfSucursalDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnfDigitosControl.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlDigitosControl.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlDigitosControl.setText("DC");

        jtfnfCuentaDomicilacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlCuentaDomiciliacion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCuentaDomiciliacion.setText("Cuenta");

        javax.swing.GroupLayout jPanelDatosDomiciliacionLayout = new javax.swing.GroupLayout(jPanelDatosDomiciliacion);
        jPanelDatosDomiciliacion.setLayout(jPanelDatosDomiciliacionLayout);
        jPanelDatosDomiciliacionLayout.setHorizontalGroup(
            jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                                .addComponent(jlSucursalDomiciliacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscarSucursalDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                                .addComponent(jlBancoDomiciliacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbBuscarBancoDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlDigitosControl)
                        .addGap(62, 62, 62)))
                .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtfnfBancoDomiciliacion, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(jtfnfSucursalDomiciliacion))
                    .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                        .addComponent(jtfnfDigitosControl, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jlCuentaDomiciliacion)
                        .addGap(27, 27, 27)
                        .addComponent(jtfnfCuentaDomicilacion, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosDomiciliacionLayout.setVerticalGroup(
            jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosDomiciliacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbBuscarBancoDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfnfBancoDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBancoDomiciliacion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBuscarSucursalDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfnfSucursalDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlSucursalDomiciliacion, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDatosDomiciliacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnfDigitosControl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlDigitosControl)
                    .addComponent(jtfnfCuentaDomicilacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCuentaDomiciliacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlFechaCobro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFechaCobro.setText("Fecha Cobro");

        jcbReciboEmitido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jcbReciboEmitido.setText("Recibo Emitido");

        jlNombreCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlNombreRepresentante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtffFechaFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtffFechaRemesa.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtffFechaCobro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtffFechaCobro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtffFechaCobroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosPrevisionLayout = new javax.swing.GroupLayout(jPanelDatosPrevision);
        jPanelDatosPrevision.setLayout(jPanelDatosPrevisionLayout);
        jPanelDatosPrevisionLayout.setHorizontalGroup(
            jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addComponent(jlCliente)
                                .addGap(18, 18, 18)
                                .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlFactura)
                            .addComponent(jlFechaFactura)
                            .addComponent(jlImporte))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfnfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtfnf2dImporte, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jtfnfFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                .addComponent(jtffFechaFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jPanelDatosDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jlNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRemesaDia)
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addComponent(jlRepresentante)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfnfRemesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                        .addComponent(jtfnfRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jlNombreRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPrevisionLayout.createSequentialGroup()
                                    .addComponent(jlFechaRemesa)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtffFechaRemesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDatosPrevisionLayout.createSequentialGroup()
                                    .addComponent(jlBancoNegociacion)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jbBuscarBancoNegociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfnfBancoNegociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(100, 100, 100)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcbReciboEmitido)
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addComponent(jlFechaCobro)
                                .addGap(18, 18, 18)
                                .addComponent(jtffFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(92, 92, 92))))
        );
        jPanelDatosPrevisionLayout.setVerticalGroup(
            jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCliente)
                        .addComponent(jbBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfnfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFactura)
                            .addComponent(jtfnfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFechaFactura)
                            .addComponent(jtffFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlImporte)
                            .addComponent(jtfnf2dImporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbBuscarBancoNegociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtfnfBancoNegociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                                .addComponent(jlBancoNegociacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addComponent(jPanelDatosDomiciliacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFechaRemesa)
                            .addComponent(jtffFechaRemesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlRemesaDia)
                            .addComponent(jtfnfRemesaDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlRepresentante)
                                .addComponent(jbBuscarRepresentante, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtfnfRepresentante)
                            .addComponent(jlNombreRepresentante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelDatosPrevisionLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelDatosPrevisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFechaCobro)
                            .addComponent(jtffFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbReciboEmitido)
                        .addGap(26, 26, 26))))
        );

        jbSalir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbDeduccionAbonos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbDeduccionAbonos.setText("Deducc.Abonos");

        jbDepuracionRiesgo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbDepuracionRiesgo.setText("Depuración Riesgo");

        jbBorrar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBorrar.setText("Borrar");

        jbGrabar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbGrabar.setText("Grabar");
        jbGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrabarActionPerformed(evt);
            }
        });

        jbAtras.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jbAdelante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N
        jbAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdelanteActionPerformed(evt);
            }
        });

        jbNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nuevo.gif"))); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jtffVencimiento.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtffVencimiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtffVencimientoFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlVencimiento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscarFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtffVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jlEfecto)
                                .addGap(18, 18, 18)
                                .addComponent(jtfnfEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jlSituacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jlCentro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelDatosPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbDeduccionAbonos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbDepuracionRiesgo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlEfecto)
                                .addComponent(jtfnfEfecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlSituacion)
                                .addComponent(jcbxSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCentro)
                                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlVencimiento)
                            .addComponent(jbBuscarFechaVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtffVencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbNuevo)))
                .addGap(18, 18, 18)
                .addComponent(jPanelDatosPrevision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDepuracionRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbDeduccionAbonos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarRepresentanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarRepresentanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbBuscarRepresentanteActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        salir();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdelanteActionPerformed
        int fechaVencimiento = util.Cadena.cadenaAfecha(jtffVencimiento.getText().trim());
	int numeroEfecto = Integer.valueOf(jtfnfEfecto.getText());
        
        String strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' ";
              //strSql += "AND EFECOB_CENTRO = " + jtfnfCentro.getText().trim() + " ";
              strSql += "AND EFECOB_VENCIM = " + fechaVencimiento + " ";
              strSql += "AND EFECOB_EFECTO > " + numeroEfecto + " ";
              strSql += "ORDER BY EFECOB_VENCIM, EFECOB_EFECTO LIMIT 1";
              
        if(BaseDatos.countRows(strSql) == 0){
            strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' ";
            //strSql += "AND EFECOB_CENTRO = " + jtfnfCentro.getText().trim() + " ";
            strSql += "AND EFECOB_VENCIM > " + fechaVencimiento + " ";
            strSql += "ORDER BY EFECOB_VENCIM, EFECOB_EFECTO LIMIT 1";
        }
             
        //Apariencia.mensajeInformativo(5, strSql);
        if(BaseDatos.countRows(strSql) > 0)
            cargaDatos(strSql);
        
    }//GEN-LAST:event_jbAdelanteActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        int fechaVencimiento = util.Cadena.cadenaAfecha(jtffVencimiento.getText().trim());
	int numeroEfecto = Integer.valueOf(jtfnfEfecto.getText());
        
        String strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' ";
              //strSql += "AND EFECOB_CENTRO = " + jtfnfCentro.getText().trim() + " ";
              strSql += "AND EFECOB_VENCIM = " + fechaVencimiento + " ";
              strSql += "AND EFECOB_EFECTO < " + numeroEfecto + " ";
              strSql += "ORDER BY EFECOB_VENCIM DESC, EFECOB_EFECTO DESC LIMIT 1";
              
        if(BaseDatos.countRows(strSql) == 0){
            strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' ";
            //strSql += "AND EFECOB_CENTRO = " + jtfnfCentro.getText().trim() + " ";
            strSql += "AND EFECOB_VENCIM < " + fechaVencimiento + " ";
            strSql += "ORDER BY EFECOB_VENCIM DESC, EFECOB_EFECTO DESC LIMIT 1";
        }
              
        //Apariencia.mensajeInformativo(5, strSql);
        if(BaseDatos.countRows(strSql) > 0)
            cargaDatos(strSql);
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbBuscarFechaVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarFechaVencimientoActionPerformed
        if (indicePrevisionesCobro == null) {
            indicePrevisionesCobro = new IndicePrevisionesCobro();
        } else {
            indicePrevisionesCobro.muestra();
        }

        efectoCobrar = indicePrevisionesCobro.getEfectoCobrar();

        //cargaPorFechaYnumeroVencimiento(efectoCobrar.getVencimiento(), efectoCobrar.getEfecto());

    }//GEN-LAST:event_jbBuscarFechaVencimientoActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        enCreacion = true;
        borrarPantalla();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrabarActionPerformed
        enCreacion = false;
    }//GEN-LAST:event_jbGrabarActionPerformed

    private void jtfnfEfectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnfEfectoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfnfEfectoActionPerformed

    private void jtffVencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtffVencimientoActionPerformed
        
    }//GEN-LAST:event_jtffVencimientoActionPerformed

    private void jtffVencimientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtffVencimientoFocusLost
        int fechaVencimiento, numeroEfecto, centro;

        fechaVencimiento = jtffVencimiento.getFechaAAAAMMDD();
        numeroEfecto = Integer.valueOf(jtfnfEfecto.getText());
        centro = Integer.valueOf(jtfnfCentro.getText());

        if (fechaVencimiento > 0 && numeroEfecto > 0) {
            String strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND ";
            strSql += "EFECOB_CENTRO = " + centro + " AND ";
            strSql += "EFECOB_VENCIM = " + fechaVencimiento + " AND ";
            strSql += "EFECOB_EFECTO = " + numeroEfecto + " LIMIT 1";

            if (BaseDatos.countRows(strSql) > 0) {
                borrarPantalla();
                cargaDatos(strSql);
            }
        }
    }//GEN-LAST:event_jtffVencimientoFocusLost

    private void jtffFechaCobroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtffFechaCobroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtffFechaCobroActionPerformed

    private void salir() {
        this.dispose();
        frameMenu.setEnabled(true);
    }    
    
    private void borrarPantalla() {
        jtffFechaCobro.setText("");
        jtffFechaFactura.setText("");
        jtffFechaRemesa.setText("");
        jtffVencimiento.setText("");
        jtfnf2dImporte.setText("0,0");
        jtfnfBancoDomiciliacion.setText("0");
        jtfnfBancoNegociacion.setText("0");
        jtfnfCentro.setText("0");
        jtfnfCliente.setText("0");
        jtfnfCuentaDomicilacion.setText("0");
        jtfnfDigitosControl.setText("0");
        jtfnfEfecto.setText("0");
        jtfnfFactura.setText("0");
        jtfnfRemesaDia.setText("0");
        jtfnfRepresentante.setText("0");
        jtfnfSucursalDomiciliacion.setText("0");
        jlNombreCliente.setText("");
        jlNombreRepresentante.setText("");
        jcbReciboEmitido.setSelected(false);
    }
    
    private void cargaInicial(){
        String strSql = "SELECT * FROM EFECOB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' ";
             // strSql += "AND EFECOB_CENTRO = " + DatosComunes.centroCont + " ";
             // No tenemos en cuenta el centro Contable con el que se entra. ????
              strSql += "ORDER BY EFECOB_VENCIM DESC LIMIT 1";
              
        cargaDatos(strSql);  
   
    }
    
    private void cargaDatos(String strSql){
        efectoCobrar.read(strSql);
        
        jtffFechaCobro.setText(util.Cadena.fechaAcadena(efectoCobrar.getFechaCobro()));
        jtffFechaFactura.setText(util.Cadena.fechaAcadena(efectoCobrar.getFechaFactura()));
        jtffFechaRemesa.setText(util.Cadena.fechaAcadena(efectoCobrar.getFechaRemesa()));
        jtffVencimiento.setText(util.Cadena.fechaAcadena(efectoCobrar.getVencimiento()));
        jtfnf2dImporte.setText(String.valueOf(efectoCobrar.getImporte()));
        jtfnfBancoDomiciliacion.setText(String.valueOf(efectoCobrar.getNumeroBanco()));
        jtfnfBancoNegociacion.setText(String.valueOf(efectoCobrar.getBanco()));
        jtfnfCentro.setText(String.valueOf(efectoCobrar.getCentro()));
        jtfnfCliente.setText(String.valueOf(efectoCobrar.getCuenta()));
        // Obtener el nombre de la cuenta del cliente
        Cuenta cuenta = new Cuenta();
        cuenta.read(efectoCobrar.getCuenta(), DatosComunes.centroCont);
        jlNombreCliente.setText(cuenta.getTitulo());
        
        jtfnfCuentaDomicilacion.setText(String.valueOf(efectoCobrar.getCuentaBancaria()));
        jtfnfDigitosControl.setText(String.valueOf(efectoCobrar.getDigitosControl()));
        jtfnfEfecto.setText(String.valueOf(efectoCobrar.getEfecto()));
        jtfnfFactura.setText(String.valueOf(efectoCobrar.getFactura()));
        jtfnfRemesaDia.setText(String.valueOf(efectoCobrar.getRemesa()));
        jtfnfRepresentante.setText(String.valueOf(efectoCobrar.getRepresentante()));
        // Obtener el nombre del representante
        Representante representante = new Representante();
        representante.read(DatosComunes.eEmpresa, DatosComunes.centroCont, efectoCobrar.getRepresentante());
        jlNombreRepresentante.setText(representante.getApellidosRazonSocial());
        
        jtfnfSucursalDomiciliacion.setText(String.valueOf(efectoCobrar.getNumeroSucursal()));
        
        if(efectoCobrar.getReciboImpreso() == 1)
            jcbReciboEmitido.setSelected(true);
        else
            jcbReciboEmitido.setSelected(false);
        
        jcbxSituacion.setSelectedIndex(efectoCobrar.getSituacion());                
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelDatosDomiciliacion;
    private javax.swing.JPanel jPanelDatosPrevision;
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscarBancoDomiciliacion;
    private javax.swing.JButton jbBuscarBancoNegociacion;
    private javax.swing.JButton jbBuscarCliente;
    private javax.swing.JButton jbBuscarFechaVencimiento;
    private javax.swing.JButton jbBuscarRepresentante;
    private javax.swing.JButton jbBuscarSucursalDomiciliacion;
    private javax.swing.JButton jbDeduccionAbonos;
    private javax.swing.JButton jbDepuracionRiesgo;
    private javax.swing.JButton jbGrabar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcbReciboEmitido;
    private javax.swing.JComboBox jcbxSituacion;
    private javax.swing.JLabel jlBancoDomiciliacion;
    private javax.swing.JLabel jlBancoNegociacion;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlCliente;
    private javax.swing.JLabel jlCuentaDomiciliacion;
    private javax.swing.JLabel jlDigitosControl;
    private javax.swing.JLabel jlEfecto;
    private javax.swing.JLabel jlFactura;
    private javax.swing.JLabel jlFechaCobro;
    private javax.swing.JLabel jlFechaFactura;
    private javax.swing.JLabel jlFechaRemesa;
    private javax.swing.JLabel jlImporte;
    private javax.swing.JLabel jlNombreCliente;
    private javax.swing.JLabel jlNombreRepresentante;
    private javax.swing.JLabel jlRemesaDia;
    private javax.swing.JLabel jlRepresentante;
    private javax.swing.JLabel jlSituacion;
    private javax.swing.JLabel jlSucursalDomiciliacion;
    private javax.swing.JLabel jlVencimiento;
    private util.JTextFieldFecha jtffFechaCobro;
    private util.JTextFieldFecha jtffFechaFactura;
    private util.JTextFieldFecha jtffFechaRemesa;
    private util.JTextFieldFecha jtffVencimiento;
    private javax.swing.JTextField jtfnf2dImporte;
    private javax.swing.JTextField jtfnfBancoDomiciliacion;
    private javax.swing.JTextField jtfnfBancoNegociacion;
    private javax.swing.JTextField jtfnfCentro;
    private javax.swing.JTextField jtfnfCliente;
    private javax.swing.JTextField jtfnfCuentaDomicilacion;
    private javax.swing.JTextField jtfnfDigitosControl;
    private javax.swing.JTextField jtfnfEfecto;
    private javax.swing.JTextField jtfnfFactura;
    private javax.swing.JTextField jtfnfRemesaDia;
    private javax.swing.JTextField jtfnfRepresentante;
    private javax.swing.JTextField jtfnfSucursalDomiciliacion;
    // End of variables declaration//GEN-END:variables
}
