/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimientos;

import general.DatosComunes;
import indices.IndiceFacturasRecibidas;
import indices.IndiceProveedores;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.util.Vector;
import javax.swing.JOptionPane;
import tablas.Cuenta;
import tablas.FacturaRecibida;
import util.Apariencia;
import util.Fecha;

/**
 *
 * @author Txus
 */
public class MantenimientoFacturasRecibidas extends util.EscapeDialog {

    private FacturaRecibida facturaRecibida;
    private IndiceProveedores ip = null;
    private IndiceFacturasRecibidas ifr = null;
    
    /**
     * Creates new form MantenimientoFacturasRecibidas
     */
    public MantenimientoFacturasRecibidas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        cargaInicial();
        
        Vector<Component> order;
        order = new Vector<>(12);
        order.add(jtffeFecha);
        order.add(jtfnfOrden);
        order.add(jtfnfCentro);
        order.add(jtfnfCuentaProveedor);
        order.add(jtfnfFactura);
        order.add(jtfnf2DBaseIvaReducido);
        order.add(jtfnf2DBaseIvaGeneral);
        order.add(jtfnf2DBaseIvaSuperreducido);
        order.add(jtfnf2DBaseIvaRegEspecial);
        order.add(jtfnf2DImporteIva);
        order.add(jtfnf2DRecargoEquivalencia);
        order.add(jtfnf2DTotal);
        MyOFocusTraversalPolicy newPolicy = new MyOFocusTraversalPolicy(order);
        this.setFocusTraversalPolicy(newPolicy);
       
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFecha = new javax.swing.JLabel();
        jtffeFecha = new util.JTextFieldFecha();
        jbBuscarFactura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfnfOrden = new util.JTextFieldNumeroFijo(5);
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(3);
        jpDatosFactura = new javax.swing.JPanel();
        jlProveedor = new javax.swing.JLabel();
        jbBuscarProveedor = new javax.swing.JButton();
        jtfnfCuentaProveedor = new util.JTextFieldNumeroFijo(9);
        jlTituloCuenta = new javax.swing.JLabel();
        jlFactura = new javax.swing.JLabel();
        jtfnfFactura = new util.JTextFieldNumeroFijo(6);
        jlReducido = new javax.swing.JLabel();
        jlGeneral = new javax.swing.JLabel();
        jlSuperreducido = new javax.swing.JLabel();
        jlRegimenEspecial = new javax.swing.JLabel();
        jlBasesIva = new javax.swing.JLabel();
        jlImporteIva = new javax.swing.JLabel();
        jlRecargoEquivalencia = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jtfnf2DBaseIvaReducido = new util.JTextFieldNumero2Decimales();
        jtfnf2DBaseIvaGeneral = new util.JTextFieldNumero2Decimales();
        jtfnf2DBaseIvaSuperreducido = new util.JTextFieldNumero2Decimales();
        jtfnf2DBaseIvaRegEspecial = new util.JTextFieldNumero2Decimales();
        jtfnf2DImporteIva = new util.JTextFieldNumero2Decimales();
        jtfnf2DRecargoEquivalencia = new util.JTextFieldNumero2Decimales();
        jtfnf2DTotal = new util.JTextFieldNumero2Decimales();
        jbSalir = new javax.swing.JButton();
        jbTotalMeses = new javax.swing.JButton();
        jbGrabar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Facturas Recibidas");
        setModal(true);
        setResizable(false);

        jlFecha.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFecha.setText("Fecha");

        jtffeFecha.setText("00.00.00");
        jtffeFecha.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtffeFecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtffeFechaFocusLost(evt);
            }
        });

        jbBuscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarFactura.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarFacturaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel1.setText("Orden");

        jtfnfOrden.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfOrden.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfOrdenFocusLost(evt);
            }
        });

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfCentro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfCentroFocusLost(evt);
            }
        });

        jpDatosFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14), new java.awt.Color(51, 51, 255))); // NOI18N

        jlProveedor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlProveedor.setText("Prov/Acreedor");

        jbBuscarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarProveedor.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBuscarProveedor.setRolloverEnabled(true);
        jbBuscarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarProveedorActionPerformed(evt);
            }
        });

        jtfnfCuentaProveedor.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlTituloCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlTituloCuenta.setForeground(new java.awt.Color(51, 51, 255));

        jlFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFactura.setText("Factura");

        jtfnfFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlReducido.setText("Reducido");

        jlGeneral.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlGeneral.setText("General");

        jlSuperreducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlSuperreducido.setText("Superreducido");

        jlRegimenEspecial.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlRegimenEspecial.setText("Reg.Especial");

        jlBasesIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlBasesIva.setText("Bases I.V.A.");

        jlImporteIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlImporteIva.setText("Importe I.V.A.");

        jlRecargoEquivalencia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlRecargoEquivalencia.setText("Recargo Equivalencia");

        jlTotal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlTotal.setText("Total");

        jtfnf2DBaseIvaReducido.setText("jTextFieldNumero2Decimales1");
        jtfnf2DBaseIvaReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnf2DBaseIvaReducido.setPreferredSize(new java.awt.Dimension(100, 25));

        jtfnf2DBaseIvaGeneral.setText("jTextFieldNumero2Decimales1");
        jtfnf2DBaseIvaGeneral.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnf2DBaseIvaGeneral.setPreferredSize(new java.awt.Dimension(100, 24));

        jtfnf2DBaseIvaSuperreducido.setText("jTextFieldNumero2Decimales1");
        jtfnf2DBaseIvaSuperreducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnf2DBaseIvaSuperreducido.setPreferredSize(new java.awt.Dimension(100, 24));

        jtfnf2DBaseIvaRegEspecial.setText("jTextFieldNumero2Decimales1");
        jtfnf2DBaseIvaRegEspecial.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnf2DBaseIvaRegEspecial.setPreferredSize(new java.awt.Dimension(100, 24));

        jtfnf2DImporteIva.setText("jTextFieldNumero2Decimales1");
        jtfnf2DImporteIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2DRecargoEquivalencia.setText("jTextFieldNumero2Decimales1");
        jtfnf2DRecargoEquivalencia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2DTotal.setText("jTextFieldNumero2Decimales1");
        jtfnf2DTotal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpDatosFacturaLayout = new javax.swing.GroupLayout(jpDatosFactura);
        jpDatosFactura.setLayout(jpDatosFacturaLayout);
        jpDatosFacturaLayout.setHorizontalGroup(
            jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlRecargoEquivalencia)
                                    .addComponent(jlImporteIva)
                                    .addComponent(jlBasesIva)
                                    .addComponent(jlTotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfnf2DBaseIvaReducido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfnf2DTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfnf2DRecargoEquivalencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtfnf2DImporteIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jtfnf2DBaseIvaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE))
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jlReducido)
                                .addGap(51, 51, 51)
                                .addComponent(jlGeneral)
                                .addGap(38, 38, 38)))
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jtfnf2DBaseIvaSuperreducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfnf2DBaseIvaRegEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlSuperreducido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlRegimenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFactura)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jtfnfCuentaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlTituloCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50))
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jtfnfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jpDatosFacturaLayout.setVerticalGroup(
            jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbBuscarProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosFacturaLayout.createSequentialGroup()
                            .addComponent(jlTituloCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addComponent(jlProveedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtfnfCuentaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFactura)
                    .addComponent(jtfnfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlReducido)
                    .addComponent(jlGeneral)
                    .addComponent(jlSuperreducido)
                    .addComponent(jlRegimenEspecial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfnf2DBaseIvaReducido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlBasesIva))
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfnf2DBaseIvaGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfnf2DBaseIvaSuperreducido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfnf2DBaseIvaRegEspecial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnf2DImporteIva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlImporteIva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnf2DRecargoEquivalencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlRecargoEquivalencia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfnf2DTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTotal)))
        );

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.setPreferredSize(new java.awt.Dimension(30, 30));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbTotalMeses.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbTotalMeses.setText("Tot/Meses");

        jbGrabar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbGrabar.setText("Grabar");
        jbGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrabarActionPerformed(evt);
            }
        });

        jbBorrar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N
        jbAtras.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N
        jbAdelante.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtffeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfnfOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlCentro)
                .addGap(18, 18, 18)
                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbTotalMeses)
                .addGap(18, 18, 18)
                .addComponent(jbGrabar)
                .addGap(18, 18, 18)
                .addComponent(jbBorrar)
                .addGap(18, 18, 18)
                .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDatosFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbBuscarFactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlFecha)
                            .addComponent(jtffeFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jtfnfOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCentro)
                        .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDatosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbBorrar)
                        .addComponent(jbGrabar)
                        .addComponent(jbTotalMeses))
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jbAdelante, jbAtras, jbBorrar, jbGrabar, jbSalir, jbTotalMeses});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdelanteActionPerformed
        
        String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN > " + jtfnfOrden.getText().trim() + " "                      
                      + "ORDER BY FACREC_ORDEN ASC "
                      + "LIMIT 1";
        
        if(facturaRecibida.read(strSql) == true)
            cargaDatos(facturaRecibida);
        else{
            // Significa que hemos acabado TODAS las facturas o
            // que hemos acabado con las de esa fecha y tenemos que empezar
            // con orden > 0 y siguiente fecha
            
            strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA > " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN > 0 "                      
                      + "ORDER BY FACREC_ORDEN ASC "
                      + "LIMIT 1";
            
            if(facturaRecibida.read(strSql) == true)
                cargaDatos(facturaRecibida);
        }
    }//GEN-LAST:event_jbAdelanteActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
       
        String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN < " + jtfnfOrden.getText().trim() + " "                      
                      + "ORDER BY FACREC_ORDEN DESC "
                      + "LIMIT 1";
        
        if(facturaRecibida.read(strSql) == true)
            cargaDatos(facturaRecibida);
        else{
            // Significa que hemos acabado TODAS las facturas o
            // que hemos acabado con las de esa fecha y tenemos que empezar
            // con orden > 0 y siguiente fecha
            
            strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA < " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN <  99999 "                      
                      + "ORDER BY FACREC_FECHA DESC, FACREC_ORDEN DESC "
                      + "LIMIT 1";
            
            if(facturaRecibida.read(strSql) == true)
                cargaDatos(facturaRecibida);
        }
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrabarActionPerformed
       
        facturaRecibida.setEmpresa(DatosComunes.eEmpresa);
        facturaRecibida.setProveedorAcreedor(jtfnfCuentaProveedor.getText().trim());
        facturaRecibida.setFecha(jtffeFecha.getFechaAAAAMMDD());
        facturaRecibida.setOrden(Integer.valueOf(jtfnfOrden.getText().trim()));
        facturaRecibida.setCentro(Integer.valueOf(jtfnfCentro.getText().trim()));
        facturaRecibida.setFactura(Integer.valueOf(jtfnfFactura.getText().trim()));
        facturaRecibida.setBase(0, jtfnf2DBaseIvaReducido.getDouble());
        facturaRecibida.setBase(1, jtfnf2DBaseIvaGeneral.getDouble());
        facturaRecibida.setBase(2, jtfnf2DBaseIvaSuperreducido.getDouble());
        facturaRecibida.setBase(3, jtfnf2DBaseIvaRegEspecial.getDouble());
        facturaRecibida.setIva(jtfnf2DImporteIva.getDouble());
        facturaRecibida.setRecargoEquivalencia(jtfnf2DRecargoEquivalencia.getDouble());
        facturaRecibida.setTotal(jtfnf2DTotal.getDouble());
        
        if(facturaRecibida.write() == true)
           Apariencia.mensajeInformativo(5, "Factura Recibida grabada correctamente."); 
    }//GEN-LAST:event_jbGrabarActionPerformed

    private void jbBuscarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarProveedorActionPerformed
        
        if(ip == null)
            ip = new IndiceProveedores();
        else
            ip.setVisible(true);
        
        if(ip.getCuenta() != null){
           Cuenta cuentaContable = new Cuenta();
           cuentaContable.read(ip.getCuenta(), Integer.valueOf(jtfnfCentro.getText().trim()));
           jlTituloCuenta.setText(cuentaContable.getTitulo());
        }
    }//GEN-LAST:event_jbBuscarProveedorActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed

        int fecha, orden, centro;

        fecha = jtffeFecha.getFechaAAAAMMDD();
        orden = Integer.valueOf(jtfnfOrden.getText().trim());
        centro = Integer.valueOf(jtfnfCentro.getText().trim());

        if (fecha == 0 || orden == 0 || centro != DatosComunes.centroCont) {
            Apariencia.mensajeInformativo(5, "<center>Debes introducir una fecha y <br>"
                    + "númerode orden válidos!!!</center>");
        } else {
            String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                    + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                    + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                    + "FACREC_ORDEN = " + orden + " "
                    + "LIMIT 1";

            if (facturaRecibida.read(strSql) == true) {
                // Damos la oportunidad de no borrar
                Object[] opciones = {"Si", "No"};

                int n = JOptionPane.showOptionDialog(this,
                        "<html><font size='4'><strong>"
                        + "Desea borrar la Recibida Emitida<br>"
                        + "Fecha : " + Fecha.fechaAcadena(fecha) + "<br>"
                        + "Orden : " + orden + "<br>"
                        + "</strong></font></html>",
                        "Borrar factura Recibida",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, // Sin Icono personalizado.
                        opciones, // Título de los botonoes
                        opciones[1]); // Botón por defecto.
                //Si
                if (n == 0) {
                    if (facturaRecibida.delete(centro, fecha, orden) > 0) {
                        Apariencia.mensajeInformativo(4, "Factura emitida borrada.");

                        // Cargamos la siguiente factura emitida
                        strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                                + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                                + "FACREC_FECHA = " + fecha + " AND "
                                + "FACREC_ORDEN > " + orden + " "
                                + "ORDER BY FACREC_ORDEN ASC "
                                + "LIMIT 1";

                        if (facturaRecibida.read(strSql) == true) {
                            cargaDatos(facturaRecibida);
                        } else {
                            // Significa que hemos acabado TODAS las facturas o
                            // que hemos acabado con las de esa fecha y tenemos que empezar
                            // con orden > 0 y siguiente fecha

                            strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                                    + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                                    + "FACREC_FECHA > " + fecha + " AND "
                                    + "FACREC_ORDEN > 0 "
                                    + "ORDER BY FACREC_ORDEN ASC "
                                    + "LIMIT 1";

                            if (facturaRecibida.read(strSql) == true) {
                                cargaDatos(facturaRecibida);
                            }
                        }
                    } else {
                        Apariencia.mensajeInformativo(4, "No se ha podido borrar la Factura Recibida!!!");
                    }
                }
            } else {
                Apariencia.mensajeInformativo(4, "No existe la Factura que quieres borrar!!!");
            }
        } 
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarFacturaActionPerformed
        
        if(ifr == null){
            ifr = new IndiceFacturasRecibidas();
        }else{
            ifr.setVisible(true);
        }
        
        if(ifr.getFacturaRecibida() != null){
            facturaRecibida = ifr.getFacturaRecibida();
            cargaDatos(facturaRecibida);
        }
            
    }//GEN-LAST:event_jbBuscarFacturaActionPerformed

    private void jtffeFechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtffeFechaFocusLost
         
        String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN = " + jtfnfOrden.getText().trim() + " "                                            
                      + "LIMIT 1";
        
        if(facturaRecibida.read(strSql) == true)
            cargaDatos(facturaRecibida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtffeFechaFocusLost

    private void jtfnfOrdenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfOrdenFocusLost
        
        String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN = " + jtfnfOrden.getText().trim() + " "                                            
                      + "LIMIT 1";
        
        if(facturaRecibida.read(strSql) == true)
            cargaDatos(facturaRecibida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtfnfOrdenFocusLost

    private void jtfnfCentroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfCentroFocusLost
        
         String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACREC_FECHA = " + jtffeFecha.getStrFechaAAAAMMDD() + " AND "
                      + "FACREC_ORDEN = " + jtfnfOrden.getText().trim() + " "                                            
                      + "LIMIT 1";
        
        if(facturaRecibida.read(strSql) == true)
            cargaDatos(facturaRecibida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtfnfCentroFocusLost

    private void borrarPantalla(){
        jlTituloCuenta.setText("");
        jtffeFecha.setText("00.00.00");
        jtfnf2DBaseIvaGeneral.setText("0,0");
        jtfnf2DBaseIvaReducido.setText("0,0");
        jtfnf2DBaseIvaRegEspecial.setText("0,0");
        jtfnf2DBaseIvaSuperreducido.setText("0,0");        
        jtfnf2DImporteIva.setText("0,0");        
        jtfnf2DRecargoEquivalencia.setText("0,0");        
        jtfnf2DTotal.setText("0,0");        
        jtfnfCentro.setText(String.valueOf(DatosComunes.centroCont));
        jtfnfCuentaProveedor.setText("0");        
        jtfnfFactura.setText("0");        
        jtfnfOrden.setText("0");        
    }
    
    private void borrarPantallaSoloDatos(){
        jlTituloCuenta.setText("");        
        jtfnf2DBaseIvaGeneral.setText("0,0");
        jtfnf2DBaseIvaReducido.setText("0,0");
        jtfnf2DBaseIvaRegEspecial.setText("0,0");
        jtfnf2DBaseIvaSuperreducido.setText("0,0");        
        jtfnf2DImporteIva.setText("0,0");        
        jtfnf2DRecargoEquivalencia.setText("0,0");        
        jtfnf2DTotal.setText("0,0");        
        jtfnfCuentaProveedor.setText("0");        
        jtfnfFactura.setText("0");            
    }
    
    private void cargaInicial(){
        borrarPantalla();
        
        facturaRecibida = new FacturaRecibida();
        
        String strSql = "SELECT * FROM FACREC WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACREC_CENTRO = " + DatosComunes.centroCont + " "
                      + "ORDER BY FACREC_FECHA DESC, FACREC_ORDEN ASC "
                      + "LIMIT 1";
        
        facturaRecibida.read(strSql);
        
        cargaDatos(facturaRecibida);
    }
    
    private void cargaDatos(FacturaRecibida fr){
        Cuenta cuentaContable = new Cuenta();
        
        jtffeFecha.setText(Fecha.fechaAcadena(fr.getFecha()));
        jtfnfOrden.setText(String.valueOf(fr.getOrden()));
        jtfnfCentro.setText(String.valueOf(fr.getCentro()));
        jtfnfCuentaProveedor.setText(fr.getProveedorAcreedor()); 
        
        // Leer cuenta contable de clientes con el nombre
        if(cuentaContable.read(fr.getProveedorAcreedor(), fr.getCentro()))
            jlTituloCuenta.setText(cuentaContable.getTitulo());
        else
            jlTituloCuenta.setText("Inexistente!!!");  
        
        jtfnfFactura.setText(String.valueOf(fr.getFactura())); 
        jtfnf2DBaseIvaReducido.setText(String.valueOf(fr.getBase(0)));
        jtfnf2DBaseIvaGeneral.setText(String.valueOf(fr.getBase(1)));
        jtfnf2DBaseIvaSuperreducido.setText(String.valueOf(fr.getBase(2)));    
        jtfnf2DBaseIvaRegEspecial.setText(String.valueOf(fr.getBase(3)));            
        jtfnf2DImporteIva.setText(String.valueOf(fr.getIva()));        
        jtfnf2DRecargoEquivalencia.setText(String.valueOf(fr.getRecargoEquivalencia()));        
        jtfnf2DTotal.setText(String.valueOf(fr.getTotal()));                                              
    }
    
    public static class MyOFocusTraversalPolicy
            extends FocusTraversalPolicy {
 
        Vector<Component> order;
 
        public MyOFocusTraversalPolicy(Vector<Component> order) {
            this.order = new Vector<Component>(order.size());
            this.order.addAll(order);
        }
 
        public Component getComponentAfter(Container focusCycleRoot,
                Component aComponent) {
            int idx = (order.indexOf(aComponent) + 1) % order.size();
            return order.get(idx);
        }
 
        public Component getComponentBefore(Container focusCycleRoot,
                Component aComponent) {
            int idx = order.indexOf(aComponent) - 1;
            if (idx < 0) {
                idx = order.size() - 1;
            }
            return order.get(idx);
        }
 
        public Component getDefaultComponent(Container focusCycleRoot) {
            return order.get(0);
        }
 
        public Component getLastComponent(Container focusCycleRoot) {
            return order.lastElement();
        }
 
        public Component getFirstComponent(Container focusCycleRoot) {
            return order.get(0);
        }
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscarFactura;
    private javax.swing.JButton jbBuscarProveedor;
    private javax.swing.JButton jbGrabar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbTotalMeses;
    private javax.swing.JLabel jlBasesIva;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlFactura;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlGeneral;
    private javax.swing.JLabel jlImporteIva;
    private javax.swing.JLabel jlProveedor;
    private javax.swing.JLabel jlRecargoEquivalencia;
    private javax.swing.JLabel jlReducido;
    private javax.swing.JLabel jlRegimenEspecial;
    private javax.swing.JLabel jlSuperreducido;
    private javax.swing.JLabel jlTituloCuenta;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JPanel jpDatosFactura;
    private util.JTextFieldFecha jtffeFecha;
    private util.JTextFieldNumero2Decimales jtfnf2DBaseIvaGeneral;
    private util.JTextFieldNumero2Decimales jtfnf2DBaseIvaReducido;
    private util.JTextFieldNumero2Decimales jtfnf2DBaseIvaRegEspecial;
    private util.JTextFieldNumero2Decimales jtfnf2DBaseIvaSuperreducido;
    private util.JTextFieldNumero2Decimales jtfnf2DImporteIva;
    private util.JTextFieldNumero2Decimales jtfnf2DRecargoEquivalencia;
    private util.JTextFieldNumero2Decimales jtfnf2DTotal;
    private util.JTextFieldNumeroFijo jtfnfCentro;
    private util.JTextFieldNumeroFijo jtfnfCuentaProveedor;
    private util.JTextFieldNumeroFijo jtfnfFactura;
    private util.JTextFieldNumeroFijo jtfnfOrden;
    // End of variables declaration//GEN-END:variables
}
