/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mantenimientos;

import general.DatosComunes;
import indices.IndiceClientesContables;
import indices.IndiceFacturasEmitidas;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.util.Vector;
import javax.swing.JOptionPane;
import tablas.Cuenta;
import tablas.FacturaEmitida;
import util.Apariencia;
import util.BaseDatos;
import util.Cadena;
import util.Fecha;

/**
 *
 * @author Txus
 */
public class MantenimientoFacturasEmitidas extends util.EscapeDialog {

    private FacturaEmitida facturaEmitida;
    private IndiceFacturasEmitidas ife = null;
    /**
     * Creates new form MantenimientoFacturasEmitidas
     */
    public MantenimientoFacturasEmitidas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        
        cargaInicial();        
        
        
        Vector<Component> order;
        order = new Vector<>(16);
        order.add(jtfnfFactura);
        order.add(jtfnfAny);
        order.add(jtffSerie);
        order.add(jtfnfCentro);
        order.add(jtfnfCodigoCliente);
        order.add(jtffeFechaFactura);
        order.add(jtfnf2dBaseIvaReducido);
        order.add(jtfnf2dBaseIvaGeneral);
        order.add(jtfnf2dBaseIVASuperReducido);
        order.add(jtfnf2dBaseREReducido);
        order.add(jtfnf2dBaseREGeneral);
        order.add(jtfnf2dImporteIva);
        order.add(jtfnf2dRecargoEquivalencia);
        order.add(jtfnf2dTotal);
        order.add(jtffNombreCliente);
        order.add(jtffNif);              
        MyOFocusTraversalPolicy newPolicy = new MyOFocusTraversalPolicy(order);
        this.setFocusTraversalPolicy(newPolicy);
        
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlFactura = new javax.swing.JLabel();
        jtfnfFactura = new util.JTextFieldNumeroFijo(6);
        jbBuscarFactura = new javax.swing.JButton();
        jlAny = new javax.swing.JLabel();
        jtfnfAny = new util.JTextFieldFijo(4);
        jtffSerie = new util.JTextFieldFijo(2);
        jlSerie = new javax.swing.JLabel();
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(3);
        jpDatosFactura = new javax.swing.JPanel();
        jlCodigoCliente = new javax.swing.JLabel();
        jbBuscarCodigoCliente = new javax.swing.JButton();
        jtfnfCodigoCliente = new util.JTextFieldFijo(7);
        jlCodigoClienteDescripcion = new javax.swing.JLabel();
        jlFechaFactura = new javax.swing.JLabel();
        jtffeFechaFactura = new util.JTextFieldFecha();
        jlReducido = new javax.swing.JLabel();
        jlGeneral = new javax.swing.JLabel();
        jlSuperreducido = new javax.swing.JLabel();
        jlBasesIva = new javax.swing.JLabel();
        jlBasesRecargoEquivalencia = new javax.swing.JLabel();
        jlImporteIva = new javax.swing.JLabel();
        jlRecargoEquivalencia = new javax.swing.JLabel();
        jlTotal = new javax.swing.JLabel();
        jtfnf2dBaseIvaReducido = new util.JTextFieldNumero2Decimales();
        jtfnf2dBaseIvaGeneral = new util.JTextFieldNumero2Decimales();
        jtfnf2dBaseIVASuperReducido = new util.JTextFieldNumero2Decimales();
        jtfnf2dBaseREReducido = new util.JTextFieldNumero2Decimales();
        jtfnf2dBaseREGeneral = new util.JTextFieldNumero2Decimales();
        jtfnf2dImporteIva = new util.JTextFieldNumero2Decimales();
        jtfnf2dRecargoEquivalencia = new util.JTextFieldNumero2Decimales();
        jtfnf2dTotal = new util.JTextFieldNumero2Decimales();
        jlNombreCliente = new javax.swing.JLabel();
        jlNif = new javax.swing.JLabel();
        jtffNombreCliente = new util.JTextFieldFijo(30);
        jtffNif = new util.JTextFieldFijo();
        jbSalir = new javax.swing.JButton();
        jbTotalMeses = new javax.swing.JButton();
        jbGrabar = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Facturas Emitidas");
        setModal(true);
        setResizable(false);

        jlFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFactura.setText("Factura");

        jtfnfFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfFactura.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfFacturaFocusLost(evt);
            }
        });
        jtfnfFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnfFacturaActionPerformed(evt);
            }
        });

        jbBuscarFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarFactura.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBuscarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarFacturaActionPerformed(evt);
            }
        });

        jlAny.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlAny.setText("Año");

        jtfnfAny.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfAny.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfAnyFocusLost(evt);
            }
        });

        jtffSerie.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtffSerie.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtffSerieFocusLost(evt);
            }
        });

        jlSerie.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlSerie.setText("Serie");

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jpDatosFactura.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(51, 51, 255))); // NOI18N
        jpDatosFactura.setMaximumSize(new java.awt.Dimension(699, 378));

        jlCodigoCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCodigoCliente.setText("Cod. Cliente");

        jbBuscarCodigoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarCodigoCliente.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBuscarCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCodigoClienteActionPerformed(evt);
            }
        });

        jtfnfCodigoCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfCodigoCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfCodigoClienteFocusLost(evt);
            }
        });
        jtfnfCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnfCodigoClienteActionPerformed(evt);
            }
        });

        jlCodigoClienteDescripcion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCodigoClienteDescripcion.setForeground(new java.awt.Color(102, 102, 255));

        jlFechaFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlFechaFactura.setText("Fecha Factura");

        jtffeFechaFactura.setText("00.00.00");
        jtffeFechaFactura.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlReducido.setText("Reducido");

        jlGeneral.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlGeneral.setText("General");

        jlSuperreducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlSuperreducido.setText("Superreducido");

        jlBasesIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlBasesIva.setText("Bases I.V.A.");

        jlBasesRecargoEquivalencia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlBasesRecargoEquivalencia.setText("Bases R. Eq.");

        jlImporteIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlImporteIva.setText("Importe I.V.A.");

        jlRecargoEquivalencia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlRecargoEquivalencia.setText("Rec.Equivalencia");

        jlTotal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlTotal.setText("Total");

        jtfnf2dBaseIvaReducido.setText("jTextFieldNumero2Decimales1");
        jtfnf2dBaseIvaReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dBaseIvaGeneral.setText("jTextFieldNumero2Decimales1");
        jtfnf2dBaseIvaGeneral.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dBaseIVASuperReducido.setText("jTextFieldNumero2Decimales1");
        jtfnf2dBaseIVASuperReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dBaseREReducido.setText("jTextFieldNumero2Decimales1");
        jtfnf2dBaseREReducido.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dBaseREGeneral.setText("jTextFieldNumero2Decimales1");
        jtfnf2dBaseREGeneral.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dImporteIva.setText("jTextFieldNumero2Decimales1");
        jtfnf2dImporteIva.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dRecargoEquivalencia.setText("jTextFieldNumero2Decimales1");
        jtfnf2dRecargoEquivalencia.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2dTotal.setText("jTextFieldNumero2Decimales1");
        jtfnf2dTotal.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlNombreCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlNombreCliente.setText("Cliente");

        jlNif.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlNif.setText("N.I.F.");

        jtffNombreCliente.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtffNif.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jpDatosFacturaLayout = new javax.swing.GroupLayout(jpDatosFactura);
        jpDatosFactura.setLayout(jpDatosFacturaLayout);
        jpDatosFacturaLayout.setHorizontalGroup(
            jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfnf2dTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlRecargoEquivalencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtfnf2dRecargoEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlImporteIva)
                                .addGap(40, 40, 40)
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtfnf2dBaseIvaReducido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jlReducido)
                                        .addComponent(jtfnf2dBaseREReducido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jtfnf2dImporteIva, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlGeneral)
                                    .addComponent(jtfnf2dBaseREGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfnf2dBaseIvaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlNif)
                                    .addComponent(jlNombreCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtffNif, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtffNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                                .addComponent(jlCodigoCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbBuscarCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlFechaFactura))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfnfCodigoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(jtffeFechaFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jlCodigoClienteDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlBasesIva)
                            .addComponent(jlBasesRecargoEquivalencia))
                        .addGap(308, 308, 308)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlSuperreducido)
                            .addComponent(jtfnf2dBaseIVASuperReducido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpDatosFacturaLayout.setVerticalGroup(
            jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCodigoCliente)
                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfnfCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCodigoClienteDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbBuscarCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlFechaFactura)
                    .addComponent(jtffeFechaFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlReducido)
                    .addComponent(jlGeneral)
                    .addComponent(jlSuperreducido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBasesIva)
                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfnf2dBaseIvaReducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfnf2dBaseIvaGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfnf2dBaseIVASuperReducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfnf2dBaseREGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlBasesRecargoEquivalencia)
                        .addComponent(jtfnf2dBaseREReducido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlImporteIva)
                    .addComponent(jtfnf2dImporteIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnf2dRecargoEquivalencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlRecargoEquivalencia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnf2dTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlTotal)
                            .addComponent(jlNif)
                            .addComponent(jtffNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpDatosFacturaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpDatosFacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlNombreCliente)
                            .addComponent(jtffNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.setPreferredSize(new java.awt.Dimension(30, 30));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbTotalMeses.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbTotalMeses.setText("Tot/Meses");

        jbGrabar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbGrabar.setText("Grabar");
        jbGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGrabarActionPerformed(evt);
            }
        });

        jbBorrar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBorrar.setText("Borrar");
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N
        jbAtras.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N
        jbAdelante.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jlFactura)
                        .addGap(18, 18, 18)
                        .addComponent(jtfnfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jlAny)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfnfAny, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jlSerie)
                        .addGap(18, 18, 18)
                        .addComponent(jtffSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jlCentro)
                        .addGap(18, 18, 18)
                        .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jbTotalMeses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(jbGrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpDatosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlFactura)
                        .addComponent(jtfnfFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfnfAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtffSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlSerie)
                            .addComponent(jlCentro)
                            .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlAny)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpDatosFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbTotalMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarPantalla() {
        jtffNif.setText("");
        jtffNombreCliente.setText("");
        jtffSerie.setText("");
        jtffeFechaFactura.setText("00.00.00");
        jtfnf2dBaseIVASuperReducido.setText("0,0");
        jtfnf2dBaseIvaGeneral.setText("0,0");
        jtfnf2dBaseIvaReducido.setText("0,0");
        jtfnf2dBaseREGeneral.setText("0,0");
        jtfnf2dBaseREReducido.setText("0,0");
        jtfnf2dImporteIva.setText("0,0");
        jtfnf2dRecargoEquivalencia.setText("0,0");
        jtfnf2dTotal.setText("0,0");
        jtfnfAny.setText("0");
        jtfnfCentro.setText(String.valueOf(DatosComunes.centroCont));
        jtfnfCodigoCliente.setText("0");
        jtfnfFactura.setText("0");

    }
    
    private void borrarPantallaSoloDatos() {
        jtffNif.setText("");
        jtffNombreCliente.setText("");       
        jtffeFechaFactura.setText("00.00.00");
        jtfnf2dBaseIVASuperReducido.setText("0,0");
        jtfnf2dBaseIvaGeneral.setText("0,0");
        jtfnf2dBaseIvaReducido.setText("0,0");
        jtfnf2dBaseREGeneral.setText("0,0");
        jtfnf2dBaseREReducido.setText("0,0");
        jtfnf2dImporteIva.setText("0,0");
        jtfnf2dRecargoEquivalencia.setText("0,0");
        jtfnf2dTotal.setText("0,0");
        jtfnfCodigoCliente.setText("0");        
    }
    
    
    
    private void cargaInicial(){
        
        borrarPantalla();
        
        facturaEmitida = new FacturaEmitida();
        
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " "
                      + "ORDER BY FACEMI_ANY DESC, FACEMI_FACTURA DESC "
                      + "LIMIT 1";
        
        facturaEmitida.read(strSql);
        
        cargaDatos(facturaEmitida);
                
    }
    
    private void cargaDatos(FacturaEmitida fe){
        Cuenta cuentaContable = new Cuenta();
        
        jtfnfFactura.setText(String.valueOf(fe.getFactura()));
        jtfnfAny.setText(String.valueOf(fe.getAño()));
        jtffSerie.setText(fe.getSerie());
        jtfnfCentro.setText(String.valueOf(fe.getCentro()));
        jtfnfCodigoCliente.setText(String.valueOf(fe.getCliente()));
        // Leer cuenta contable de clientes con el nombre
        if(cuentaContable.read("43" + Cadena.enteroCerosIzquierda(fe.getCliente(), 7), fe.getCentro()))
            jlCodigoClienteDescripcion.setText(cuentaContable.getTitulo());
        else
            jlCodigoClienteDescripcion.setText("");        
        
        jtffeFechaFactura.setText(Fecha.fechaAcadena(fe.getFecha()));
        jtfnf2dBaseIvaGeneral.setText(String.valueOf(fe.getBaseIva(1)));
        jtfnf2dBaseIvaReducido.setText(String.valueOf(fe.getBaseIva(0)));
        jtfnf2dBaseIVASuperReducido.setText(String.valueOf(fe.getBaseIva(2)));
        jtfnf2dBaseREGeneral.setText(String.valueOf(fe.getBaseRecargoEquivalencia(1)));
        jtfnf2dBaseREReducido.setText(String.valueOf(fe.getBaseRecargoEquivalencia(0)));
        jtfnf2dImporteIva.setText(String.valueOf(fe.getIva()));
        jtfnf2dRecargoEquivalencia.setText(String.valueOf(fe.getRecargoEquivalencia()));
        jtfnf2dTotal.setText(String.valueOf(fe.getTotal()));
        jtffNombreCliente.setText(fe.getNombreCliente());        
        jtffNif.setText(fe.getNif());
    }
    
    private void jtfnfCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnfCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnfCodigoClienteActionPerformed

    private void jbAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdelanteActionPerformed
        
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACEMI_ANY >= " + jtfnfAny.getText() + " AND "
                      + "FACEMI_FACTURA > " + jtfnfFactura.getText() + " AND "
                      + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "
                      + "ORDER BY FACEMI_ANY ASC, FACEMI_FACTURA ASC "
                      + "LIMIT 1";
        
        if(facturaEmitida.read(strSql))
            cargaDatos(facturaEmitida);
    }//GEN-LAST:event_jbAdelanteActionPerformed

    private void jbGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGrabarActionPerformed
        
        facturaEmitida.setEmpresa(DatosComunes.eEmpresa);
        facturaEmitida.setCliente(Integer.valueOf(jtfnfCodigoCliente.getText().trim()));
        facturaEmitida.setAño(Integer.valueOf(jtfnfAny.getText().trim()));
        facturaEmitida.setSerie(jtffSerie.getText().trim());
        facturaEmitida.setCentro(Integer.valueOf(jtfnfCentro.getText().trim()));
        facturaEmitida.setFecha(jtffeFechaFactura.getFechaAAAAMMDD());
        facturaEmitida.setNombreCliente(jtffNombreCliente.getText().trim());
        facturaEmitida.setNif(jtffNif.getText().trim());
        facturaEmitida.setBaseIva(1, jtfnf2dBaseIvaGeneral.getDouble());
        facturaEmitida.setBaseIva(0, jtfnf2dBaseIvaReducido.getDouble());
        facturaEmitida.setBaseIva(2, jtfnf2dBaseIVASuperReducido.getDouble());
        facturaEmitida.setBaseRecargoEquivalencia(0, jtfnf2dBaseREReducido.getDouble());
        facturaEmitida.setBaseRecargoEquivalencia(1, jtfnf2dBaseREGeneral.getDouble());
        // Creo que el campo de Base Recargo Equivalencia Superreducido (indice = 2)
        // siempre es 0 ????
        //facturaEmitida.setBaseRecargoEquivalencia(2, 0.0);
        facturaEmitida.setIva(jtfnf2dImporteIva.getDouble());
        facturaEmitida.setRecargoEquivalencia(jtfnf2dRecargoEquivalencia.getDouble());
        facturaEmitida.setTotal(jtfnf2dTotal.getDouble());
        if(facturaEmitida.write())
            Apariencia.mensajeInformativo(5, "Factura Emitida grabada correctamente.");
    }//GEN-LAST:event_jbGrabarActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACEMI_ANY <= " + jtfnfAny.getText() + " AND "
                      + "FACEMI_FACTURA < " + jtfnfFactura.getText() + " AND "
                      + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "
                      + "ORDER BY FACEMI_ANY DESC, FACEMI_FACTURA DESC "
                      + "LIMIT 1";
        
        if(facturaEmitida.read(strSql) == true)
            cargaDatos(facturaEmitida);
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbBuscarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarFacturaActionPerformed
        
        if(ife == null)
            ife = new IndiceFacturasEmitidas();
        else
            ife.setVisible(true);
        
        if(ife.getFacturaEmitida() != null){
            facturaEmitida = ife.getFacturaEmitida();
            cargaDatos(facturaEmitida);
        }
        
    }//GEN-LAST:event_jbBuscarFacturaActionPerformed

    private void jtfnfFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnfFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfnfFacturaActionPerformed

    private void jtfnfFacturaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfFacturaFocusLost
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACEMI_ANY = " + jtfnfAny.getText() + " AND "
                      + "FACEMI_FACTURA = " + jtfnfFactura.getText() + " AND "
                      + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "                      
                      + "LIMIT 1";
        
        if(facturaEmitida.read(strSql) == true)
            cargaDatos(facturaEmitida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtfnfFacturaFocusLost

    private void jtfnfAnyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfAnyFocusLost
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACEMI_ANY = " + jtfnfAny.getText() + " AND "
                      + "FACEMI_FACTURA = " + jtfnfFactura.getText() + " AND "
                      + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "                      
                      + "LIMIT 1";
        
        if(facturaEmitida.read(strSql) == true)
            cargaDatos(facturaEmitida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtfnfAnyFocusLost

    private void jtffSerieFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtffSerieFocusLost
        String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                      + "FACEMI_ANY = " + jtfnfAny.getText() + " AND "
                      + "FACEMI_FACTURA = " + jtfnfFactura.getText() + " AND "
                      + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "                      
                      + "LIMIT 1";
        
        if(facturaEmitida.read(strSql) == true)
            cargaDatos(facturaEmitida);
        else
            borrarPantallaSoloDatos();
    }//GEN-LAST:event_jtffSerieFocusLost

    private void jbBuscarCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCodigoClienteActionPerformed
        
        String cuentaCliente;
        
        IndiceClientesContables icc = new IndiceClientesContables();
         
        cuentaCliente = icc.getCuenta();
        
        if(cuentaCliente != null){
            Cuenta cuenta = new Cuenta();
            if(cuenta.read(cuentaCliente, DatosComunes.centroCont) == true){
                // Quitamos el 43 inicial de la Cuenta Contable
                // Demasiado lío, para setText, tiene que ser String, por ello
                // hacemos el Integer.valueOf de la cuenta (String) si el 43  :-(
                jtfnfCodigoCliente.setText(String.valueOf(Integer.valueOf(cuentaCliente.substring(2, cuentaCliente.length()))));
                jlCodigoClienteDescripcion.setText(cuenta.getTitulo());
            }
        }        
    }//GEN-LAST:event_jbBuscarCodigoClienteActionPerformed

    private void jtfnfCodigoClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfCodigoClienteFocusLost
        
        long cliente;
        String cuentaCliente;
        Cuenta cuenta = new Cuenta();        
        
        cliente = Long.valueOf(jtfnfCodigoCliente.getText().trim());
        cuentaCliente = "43" + Cadena.enteroCerosIzquierda(cliente, 7);
        if(cuenta.read(cuentaCliente, DatosComunes.centroCont) == true){
           jlCodigoClienteDescripcion.setText(cuenta.getTitulo()); 
        }
        
    }//GEN-LAST:event_jtfnfCodigoClienteFocusLost

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed

        int factura, any, centro;
        String serie = "";

        factura = Integer.valueOf(jtfnfFactura.getText().trim());
        any = Integer.valueOf(jtfnfAny.getText().trim());
        centro = Integer.valueOf(jtfnfCentro.getText().trim());
        serie = jtffSerie.getText().trim();

        if (factura == 0 || any == 0 || centro != DatosComunes.centroCont) {
            Apariencia.mensajeInformativo(5, "<center>Debes introducir un número de Factura y <br>"
                    + "un año válidos!!!</center>");
        } else {
            String strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                    + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                    + "FACEMI_ANY = " + any + " AND "
                    + "FACEMI_FACTURA = " + factura + " AND "
                    + "FACEMI_SERIE = '" + serie + "' AND "
                    + "FACEMI_CENTRO = " + centro + " "
                    + "LIMIT 1";

            if (facturaEmitida.read(strSql) == true) {
                // Damos la oportunidad de no borrar
                Object[] opciones = {"Si", "No"};

                int n = JOptionPane.showOptionDialog(this,
                        "<html><font size='4'><strong>"
                        + "Desea borrar la Factura Emitida<br>"
                        + "Número : " + factura + "<br>"
                        + "Año    : " + any + "<br>"
                        + "Serie  : " + serie + "<br>"
                        + "</strong></font></html>",
                        "Borrar factura Emitida",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null, // Sin Icono personalizado.
                        opciones, // Título de los botonoes
                        opciones[1]); // Botón por defecto.
                //Si
                if (n == 0) {
                    if (facturaEmitida.delete(centro, factura, any, serie) > 0) {
                        Apariencia.mensajeInformativo(4, "Factura emitida borrada.");

                        // Cargamos la siguiente factura emitida
                        strSql = "SELECT * FROM FACEMI WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                                + "FACEMI_CENTRO = " + DatosComunes.centroCont + " AND "
                                + "FACEMI_ANY >= " + jtfnfAny.getText() + " AND "
                                + "FACEMI_FACTURA > " + jtfnfFactura.getText() + " AND "
                                + "FACEMI_SERIE = '" + jtffSerie.getText() + "' "
                                + "ORDER BY FACEMI_ANY ASC, FACEMI_FACTURA ASC "
                                + "LIMIT 1";

                        if (facturaEmitida.read(strSql)) {
                            cargaDatos(facturaEmitida);
                        }
                    } else {
                        Apariencia.mensajeInformativo(4, "No se ha podido borrar la Factura Emitida!!!");
                    }
                }
            } else {
                Apariencia.mensajeInformativo(4, "No existe la Factura que quieres borrar!!!");
            }
        }
    }//GEN-LAST:event_jbBorrarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

        public static class MyOFocusTraversalPolicy
            extends FocusTraversalPolicy {
 
        Vector<Component> order;
 
        public MyOFocusTraversalPolicy(Vector<Component> order) {
            this.order = new Vector<Component>(order.size());
            this.order.addAll(order);
        }
 
        public Component getComponentAfter(Container focusCycleRoot,
                Component aComponent) {
            int idx = (order.indexOf(aComponent) + 1) % order.size();
            return order.get(idx);
        }
 
        public Component getComponentBefore(Container focusCycleRoot,
                Component aComponent) {
            int idx = order.indexOf(aComponent) - 1;
            if (idx < 0) {
                idx = order.size() - 1;
            }
            return order.get(idx);
        }
 
        public Component getDefaultComponent(Container focusCycleRoot) {
            return order.get(0);
        }
 
        public Component getLastComponent(Container focusCycleRoot) {
            return order.lastElement();
        }
 
        public Component getFirstComponent(Container focusCycleRoot) {
            return order.get(0);
        }
    }

    
    /**
     * @param args the command line arguments
     */
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscarCodigoCliente;
    private javax.swing.JButton jbBuscarFactura;
    private javax.swing.JButton jbGrabar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbTotalMeses;
    private javax.swing.JLabel jlAny;
    private javax.swing.JLabel jlBasesIva;
    private javax.swing.JLabel jlBasesRecargoEquivalencia;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlCodigoCliente;
    private javax.swing.JLabel jlCodigoClienteDescripcion;
    private javax.swing.JLabel jlFactura;
    private javax.swing.JLabel jlFechaFactura;
    private javax.swing.JLabel jlGeneral;
    private javax.swing.JLabel jlImporteIva;
    private javax.swing.JLabel jlNif;
    private javax.swing.JLabel jlNombreCliente;
    private javax.swing.JLabel jlRecargoEquivalencia;
    private javax.swing.JLabel jlReducido;
    private javax.swing.JLabel jlSerie;
    private javax.swing.JLabel jlSuperreducido;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JPanel jpDatosFactura;
    private util.JTextFieldFijo jtffNif;
    private util.JTextFieldFijo jtffNombreCliente;
    private util.JTextFieldFijo jtffSerie;
    private util.JTextFieldFecha jtffeFechaFactura;
    private util.JTextFieldNumero2Decimales jtfnf2dBaseIVASuperReducido;
    private util.JTextFieldNumero2Decimales jtfnf2dBaseIvaGeneral;
    private util.JTextFieldNumero2Decimales jtfnf2dBaseIvaReducido;
    private util.JTextFieldNumero2Decimales jtfnf2dBaseREGeneral;
    private util.JTextFieldNumero2Decimales jtfnf2dBaseREReducido;
    private util.JTextFieldNumero2Decimales jtfnf2dImporteIva;
    private util.JTextFieldNumero2Decimales jtfnf2dRecargoEquivalencia;
    private util.JTextFieldNumero2Decimales jtfnf2dTotal;
    private util.JTextFieldFijo jtfnfAny;
    private util.JTextFieldNumeroFijo jtfnfCentro;
    private util.JTextFieldFijo jtfnfCodigoCliente;
    private util.JTextFieldNumeroFijo jtfnfFactura;
    // End of variables declaration//GEN-END:variables
}
