/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultasMantenimientos;

import general.DatosComunes;
import general.MysqlConnect;
import java.sql.ResultSet;
import java.sql.SQLException;
import indices.IndiceZonasCliente;
import java.awt.event.ActionEvent;
import util.EscapeDialog;
import java.sql.ResultSet;
import javax.swing.JFrame;
import tablas.ZonaCliente;
import util.BaseDatos;


/**
 *
 * @author Txus
 */
public class ConManZonas extends EscapeDialog {
    // Con esta variable definimos si estamos en una consulta (TRUE) o en
	// un mantenimiento (FALSE). Nos servirá para tener un sólo programa
	// para algunas Consultas/Mantenimientos que pueden compartir las 
	// mismas pantallas.
	private static boolean consulta;
	private static boolean enCreacion = false;
	
	private static IndiceZonasCliente izc = null;
	
	public static ResultSet rs = null;
	public static MysqlConnect m = null;
        
        public ZonaCliente zona = new ZonaCliente();
        
        // Definiciones de componentes de pantalla
	public JFrame frameMenu = null;
    /**
     * Creates new form ConManZonas
     * @param parent
     * @param modal
     */
    public ConManZonas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ConManZonas(boolean consultaOmantenimiento){
		ConManZonas.consulta = consultaOmantenimiento;
		//this.consulta = false;
		m = MysqlConnect.getDbCon();
		initComponents();
                borrarPantalla();
                //cargaInicial();
                this.setVisible(true);
    }
    
    public ConManZonas(JFrame parentFrame, boolean consultaOmantenimiento){
                frameMenu = parentFrame;
		ConManZonas.consulta = consultaOmantenimiento;
		//this.consulta = false;
		m = MysqlConnect.getDbCon();
		initComponents();
                borrarPantalla();
                //cargaInicial();
                this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCodigo = new javax.swing.JLabel();
        jtfnfCodigo = new util.JTextFieldNumeroFijo(2);
        jbBuscar = new javax.swing.JButton();
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(2);
        jlNombre = new javax.swing.JLabel();
        jtffNombre = new util.JTextFieldFijo(30);
        jbSalir = new javax.swing.JButton();
        jbPresupuesto = new javax.swing.JButton();
        jbEstadisticas = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbGrabar = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mantenimiento Zonas Comerciales");

        jlCodigo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCodigo.setText("Código");

        jtfnfCodigo.setColumns(2);
        jtfnfCodigo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jbBuscar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jlNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlNombre.setText("Nombre");

        jtffNombre.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jbSalir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbPresupuesto.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbPresupuesto.setText("Presupuesto");

        jbEstadisticas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbEstadisticas.setText("Estadísticas");

        jbBorrar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbBorrar.setText("Borrar");

        jbGrabar.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbGrabar.setText("Grabar");

        jbAtras.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N

        jbAdelante.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfnfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlCentro)
                                .addGap(18, 18, 18)
                                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtffNombre))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbPresupuesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addComponent(jbBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbGrabar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCodigo)
                        .addComponent(jtfnfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlCentro)
                        .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtffNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbGrabar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbPresupuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        // Si pinchamos en el botón 'Salir', 'tiramos' la pantalla
	//frameMenu.setEnabled(true);
	//pantalla.dispose();
	salir();
    }//GEN-LAST:event_jbSalirActionPerformed

    

    private void borrarPantalla(){	
	
        if(consulta){           
            jtffNombre.setEnabled(false);
            jtfnfCentro.setEnabled(false);
            jbBorrar.setVisible(false);
            jbGrabar.setVisible(false);
            jbEstadisticas.setVisible(true);
            jbPresupuesto.setVisible(false);
            
        }else{
            jtffNombre.setEnabled(true);
            jtfnfCentro.setEnabled(true);
            jbBorrar.setVisible(true);
            jbGrabar.setVisible(true);
            jbEstadisticas.setVisible(true);
            jbPresupuesto.setVisible(true);
        }
	jtfnfCodigo.setText("0");
        jtffNombre.setText("");
        jtfnfCentro.setText(String.valueOf(DatosComunes.centroCont));						
	}
    
    private void cargaInicial(){
		// Carga inicial en el primer Proveedor
		if(jtfnfCodigo.getText().length() == 0)
			jtfnfCodigo.setText("0");
		
		String strSql = "SELECT * FROM ZONCLI WHERE EMPRESA = '" + 
         DatosComunes.eEmpresa + 
         "' AND ZONCLI_ZONA >= " + jtfnfCodigo.getText();
		
		if(DatosComunes.centroCont != 0)
			strSql += " AND ZONCLI_CENTRO = " + DatosComunes.centroCont;
		
        strSql += " LIMIT 1";
		
		cargaDatos(strSql);			
	}
	
	private void cargaDatos(String strSql){		
		int numeroDeFilas = 0;
		String descripcionZona = "";				
		
		numeroDeFilas = BaseDatos.countRows(strSql);
		if(numeroDeFilas > 0){
			try {
				borrarPantalla();				
				rs = m.query(strSql);
				
				// Recorremos el recodSet para ir rellenando la tabla de marcas
				if (rs.next() == true) {
					zona.read(rs);

					// Vamos a averiguar la descripción del Banco y de la Sucursal
					IndiceZonasCliente indiceZonas = new IndiceZonasCliente();
					String strSqlIndiceBancos = "SELECT * FROM BCOIND WHERE " +
							"EMPRESA = '" + DatosComunes.eEmpresa + "' AND " +
							"BCOIND_BANCO = " + zona.getBanco() + " " +
							"ORDER BY BCOIND_BANCO, BCOIND_SUCURSAL LIMIT 1";
					indiceZonas.read(strSqlIndiceBancos);
					lDescripcionBanco.setText(indiceZonas.getDescripcion());
					// Ahora la sucursal
					strSqlIndiceBancos = "SELECT * FROM BCOIND WHERE " +
					"EMPRESA = '" + DatosComunes.eEmpresa + "' AND " +
					"BCOIND_BANCO = " + zona.getBanco() + " AND " +
					"BCOIND_SUCURSAL = '" + util.Cadena.enteroCerosIzquierda(Integer.valueOf(zona.getNumeroSucursal()), 4) + 
					"' LIMIT 1";
					indiceBancos.read(strSqlIndiceBancos);
					lDescripcionSucursal.setText(indiceBancos.getDescripcion());
					
					
					
					jtfnfCodigo.setText(String.valueOf(zona.getBanco()));
					jtfnfCentro.setText(String.valueOf(zona.getCentro()));
					jtfnfBanco.setText(String.valueOf(Cadena.enteroCerosIzquierda(zona.getBanco(), 4)));										
					jtfnfSucursal.setText(String.valueOf(Cadena.enteroCerosIzquierda(zona.getNumeroSucursal(), 4)));			
					jtfnfDigitosControl.setText(String.valueOf(Cadena.enteroCerosIzquierda(zona.getDigitoControl(), 2)));
					jtfnfCuenta.setText(String.valueOf(Cadena.enteroCerosIzquierda(Long.valueOf(zona.getCuenta()), 10)));
					jtffContacto.setText(zona.getContacto());
					jtffTelefono.setText(zona.getTelefono());
					jtffFax.setText(zona.getFax());
					jtffEmail.setText(zona.getEmail());
					jtfn2dConcedido.setText(String.valueOf(zona.getConcedido()));
					jtfn2dRiesgo.setText(String.valueOf(zona.getTotalRiesgo()));
					jtfn2dDisponible.setText(String.valueOf(zona.getConcedido() - zona.getTotalRiesgo()));
					
					// Para saber si el banco esta ACTIVO, tenemos que mirar en su cuenta contable
					Cuenta cuenta = new Cuenta();
					cuenta.read("572" + "00" + Cadena.enteroCerosIzquierda(zona.getBanco(), 4), DatosComunes.centroCont);
					if(cuenta.getActivo() == 1)
						jcbActivado.setSelected(true);
					else
						jcbActivado.setSelected(false);
				}
			} catch (SQLException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		}
	}
    
    private void salir(){
		this.dispose();
		frameMenu.setEnabled(true);		
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEstadisticas;
    private javax.swing.JButton jbGrabar;
    private javax.swing.JButton jbPresupuesto;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JTextField jtffNombre;
    private javax.swing.JTextField jtfnfCentro;
    private javax.swing.JTextField jtfnfCodigo;
    // End of variables declaration//GEN-END:variables
}
