/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import consultasMantenimientos.ConManBancos;
import consultasMantenimientos.ConManClientes;
import consultasMantenimientos.ConManProveedor;
import consultasMantenimientos.ConManRepresentantes;
import general.DatosComunes;
import indices.IndiceAcumuladosContables;
import indices.IndiceCuentas;
import indices.IndiceMovimientosContables;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.util.Vector;
import mantenimientos.ManNotas;
import tablas.Cuenta;
import util.Apariencia;

/**
 *
 * @author Txus
 */
public class ConsultaCuentas extends util.EscapeDialog {

    private IndiceCuentas indiceCuentas;
    private Cuenta cuenta;
    private ManNotas mantenimientoNotas = null;
    private ConManClientes consultaClientes = null;
    private ConManProveedor consultaProveedores = null;
    private ConManRepresentantes consultaRepresentantes = null;
    private ConManBancos consultaBancos = null;
    private IndiceAcumuladosContables indiceAcumuladosContables = null;
    private IndiceMovimientosContables indiceMovimientosContables = null;
    
    /**
     * Creates new form ConsultaCuentas
     */
    public ConsultaCuentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargaInicial();
        
        Vector<Component> order;
        order = new Vector<>(2);
        order.add(jtfnfCuenta);       
        MyOFocusTraversalPolicy newPolicy = new MyOFocusTraversalPolicy(order);
        this.setFocusTraversalPolicy(newPolicy);
        
        jtffTitulo.setEditable(false);
        jcbActivado.setEnabled(false);
        jtfnfCentro.setEditable(false);
        jtfnf2DSaldoActual.setEditable(false);
        jtfnf2DSaldoUltimaDepuracion.setEditable(false);      
        
        
        this.setVisible(true);
    }

    private void borrarPantalla(){
        jtfnfCuenta.setText("0");
        jtffTitulo.setText("");
        jtfnfCentro.setText(String.valueOf(DatosComunes.centroCont));
        jcbActivado.setSelected(true);
        jtfnf2DSaldoActual.setText("0,0");
        jtfnf2DSaldoUltimaDepuracion.setText("0,0");
    }
    
    private void cargaInicial(){
        borrarPantalla();
        
        cuenta = new Cuenta();
        
        String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "CONTAB_CENTRO = " + DatosComunes.centroCont + " "
                      + "ORDER BY CONTAB_CUENTA ASC, CONTAB_GRADO ASC LIMIT 1";
        
        cuenta.read(strSql);
        
        cargaDatos(cuenta);
        
        // Comprobamos si tiene las cuentas superiores para no permitir crear 
        // una cuenta de grado inferior sin cuentas superiores.
        if(Integer.valueOf(cuenta.getGrado()) > 1)
            if(cuenta.existenCuentasSuperiores(cuenta.getCuenta()) == false)
                Apariencia.mensajeInformativo(4, "<center>Faltan cuentas superiores!!!<br>Crear cuentas supeirores primero!!!</center>");
    }
    
    private void cargaDatos(Cuenta c){
        jtfnfCuenta.setText(c.getCuenta());
        jtffTitulo.setText(c.getTitulo());
        jtfnfCentro.setText(String.valueOf(c.getCentro()));
        if(c.getActivo() == 1)
            jcbActivado.setSelected(true);
        else
            jcbActivado.setSelected(false);
        jtfnf2DSaldoActual.setText(String.valueOf(c.getSaldo()));
        jtfnf2DSaldoUltimaDepuracion.setText(String.valueOf(c.getSaldoUltimaDepuracion()));     
        // Las cuentas sólo pueden tener movimientos si son de tercer grado.
        if(c.getGrado().equalsIgnoreCase("3"))
            jbMovimientos.setEnabled(true);
        else
            jbMovimientos.setEnabled(false);
        
        if(c.getExtenOtroFichero() > 0 && c.getGrado().equalsIgnoreCase("3")){
            switch(c.getExtenOtroFichero()){
                case 1: consultaClientes = new ConManClientes(true, c.getCuenta());
                    break;
                case 2: consultaProveedores = new ConManProveedor(true, c.getCuenta());
                    break;
                case 3: consultaRepresentantes = new ConManRepresentantes(true, c.getCuenta());
                    break;    
                case 4: consultaBancos = new ConManBancos(true, c.getCuenta());
                    break;   
            }
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCuenta = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbBuscarCuenta = new javax.swing.JButton();
        jtfnfCuenta = new util.JTextFieldNumeroFijo(9);
        jtffTitulo = new util.JTextFieldFijo(30);
        jcbActivado = new javax.swing.JCheckBox();
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(3);
        jbNotas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlNotas = new javax.swing.JLabel();
        jlUltimaDepuracion = new javax.swing.JLabel();
        jtfnf2DSaldoActual = new util.JTextFieldNumero2Decimales();
        jtfnf2DSaldoUltimaDepuracion = new util.JTextFieldNumero2Decimales();
        jbSalir = new javax.swing.JButton();
        jbAcumuladoContable = new javax.swing.JButton();
        jbMovimientos = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Cuentas");

        jlCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCuenta.setText("Cuenta");

        jlTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlTitulo.setText("Título");

        jbBuscarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarCuenta.setPreferredSize(new java.awt.Dimension(30, 30));
        jbBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCuentaActionPerformed(evt);
            }
        });

        jtfnfCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jtfnfCuenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfnfCuentaFocusLost(evt);
            }
        });
        jtfnfCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfnfCuentaActionPerformed(evt);
            }
        });

        jtffTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jcbActivado.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jcbActivado.setText("Activado");

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jbNotas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbNotas.setText("Notas");
        jbNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNotasActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        jlNotas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlNotas.setText("Actual");

        jlUltimaDepuracion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlUltimaDepuracion.setText("Ultima Depuración");

        jtfnf2DSaldoActual.setText("jTextFieldNumero2Decimales1");
        jtfnf2DSaldoActual.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2DSaldoUltimaDepuracion.setText("jTextFieldNumero2Decimales2");
        jtfnf2DSaldoUltimaDepuracion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUltimaDepuracion)
                    .addComponent(jlNotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfnf2DSaldoActual, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jtfnf2DSaldoUltimaDepuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNotas)
                    .addComponent(jtfnf2DSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUltimaDepuracion)
                    .addComponent(jtfnf2DSaldoUltimaDepuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.setPreferredSize(new java.awt.Dimension(30, 30));
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbAcumuladoContable.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAcumuladoContable.setText("Acumulado Contable");
        jbAcumuladoContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAcumuladoContableActionPerformed(evt);
            }
        });

        jbMovimientos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbMovimientos.setText("Movimientos");
        jbMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMovimientosActionPerformed(evt);
            }
        });

        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N
        jbAtras.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtrasActionPerformed(evt);
            }
        });

        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N
        jbAdelante.setPreferredSize(new java.awt.Dimension(30, 30));
        jbAdelante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdelanteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jbAcumuladoContable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbMovimientos)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtffTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(jbNotas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfnfCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(jcbActivado)
                                .addGap(66, 66, 66)
                                .addComponent(jlCentro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCuenta)
                            .addComponent(jbBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnfCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbActivado)
                            .addComponent(jlCentro)
                            .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTitulo)
                            .addComponent(jtffTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNotas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbAcumuladoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCuentaActionPerformed
        
        if(indiceCuentas == null)
            indiceCuentas = new IndiceCuentas();
        else{
            indiceCuentas.recargarTabla();
            indiceCuentas.setVisible(true);
        }
        
        // El indice de cuentas devuelve "" si hemos salido pulsando ESCAPE
        if(indiceCuentas.getCuenta().length() > 1){
            cuenta.read(indiceCuentas.getCuenta(), DatosComunes.centroCont);
            cargaDatos(cuenta);
        }
    }//GEN-LAST:event_jbBuscarCuentaActionPerformed

    private void jbAdelanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdelanteActionPerformed
        
        String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                + "CONTAB_CENTRO = " + DatosComunes.centroCont + " AND "
                + "CONTAB_CUENTA > '" + jtfnfCuenta.getText().trim() + "' "
                + "ORDER BY CONTAB_CUENTA ASC, CONTAB_GRADO ASC LIMIT 1";

        if (cuenta.read(strSql) > 0) {
            cargaDatos(cuenta);
        }
    }//GEN-LAST:event_jbAdelanteActionPerformed

    private void jbAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtrasActionPerformed
        
        String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                + "CONTAB_CENTRO = " + DatosComunes.centroCont + " AND "
                + "CONTAB_CUENTA < '" + jtfnfCuenta.getText().trim() + "' "
                + "ORDER BY CONTAB_CUENTA DESC, CONTAB_GRADO DESC LIMIT 1";

        if (cuenta.read(strSql) > 0) {
            cargaDatos(cuenta);
        }
    }//GEN-LAST:event_jbAtrasActionPerformed

    private void jbNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNotasActionPerformed
        if (cuenta.getCuenta().length() > 0) {
            if (mantenimientoNotas == null) {
                mantenimientoNotas = new ManNotas("CONTAB", cuenta.getCuenta(), cuenta.getTitulo());
            }else{
                mantenimientoNotas.recargaNota("CONTAB", cuenta.getCuenta(), cuenta.getTitulo());
            }                
        }
    }//GEN-LAST:event_jbNotasActionPerformed

    private void jbAcumuladoContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAcumuladoContableActionPerformed
        
        if(indiceAcumuladosContables == null){
            indiceAcumuladosContables = new IndiceAcumuladosContables(cuenta.getCuenta().trim(), cuenta.getTitulo().trim());
        }else{
            indiceAcumuladosContables.recargaAcumulados(cuenta.getCuenta().trim(), cuenta.getTitulo().trim());
        }
    }//GEN-LAST:event_jbAcumuladoContableActionPerformed

    private void jbMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMovimientosActionPerformed
        
        if(indiceMovimientosContables == null){
            indiceMovimientosContables = new IndiceMovimientosContables(cuenta.getCuenta().trim());            
        }else{
            indiceMovimientosContables.recargarMovimientos(cuenta.getCuenta().trim());
        }
        
    }//GEN-LAST:event_jbMovimientosActionPerformed

    private void jtfnfCuentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfnfCuentaFocusLost
        
        String strCuenta;

        strCuenta = jtfnfCuenta.getText().trim();

        if (strCuenta.length() > 0) {
            String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                    + "CONTAB_CENTRO = " + DatosComunes.centroCont + " AND "
                    + "CONTAB_CUENTA = '" + strCuenta + "' "
                    + "LIMIT 1";

            if (cuenta.read(strSql) > 0) {
                cargaDatos(cuenta);
            }
        }
    }//GEN-LAST:event_jtfnfCuentaFocusLost

    private void jtfnfCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfnfCuentaActionPerformed
       
        String strCuenta;

        strCuenta = jtfnfCuenta.getText().trim();

        if (strCuenta.length() > 0) {
            String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                    + "CONTAB_CENTRO = " + DatosComunes.centroCont + " AND "
                    + "CONTAB_CUENTA = '" + strCuenta + "' "
                    + "LIMIT 1";

            if (cuenta.read(strSql) > 0) {
                cargaDatos(cuenta);
            }else{
                borrarPantalla();
            }
        }
    }//GEN-LAST:event_jtfnfCuentaActionPerformed
   
    

    public static class MyOFocusTraversalPolicy
            extends FocusTraversalPolicy {
 
        Vector<Component> order;
 
        public MyOFocusTraversalPolicy(Vector<Component> order) {
            this.order = new Vector<Component>(order.size());
            this.order.addAll(order);
        }
 
        public Component getComponentAfter(Container focusCycleRoot,
                Component aComponent) {
            int idx = (order.indexOf(aComponent) + 1) % order.size();
            return order.get(idx);
        }
 
        public Component getComponentBefore(Container focusCycleRoot,
                Component aComponent) {
            int idx = order.indexOf(aComponent) - 1;
            if (idx < 0) {
                idx = order.size() - 1;
            }
            return order.get(idx);
        }
 
        public Component getDefaultComponent(Container focusCycleRoot) {
            return order.get(0);
        }
 
        public Component getLastComponent(Container focusCycleRoot) {
            return order.lastElement();
        }
 
        public Component getFirstComponent(Container focusCycleRoot) {
            return order.get(0);
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAcumuladoContable;
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBuscarCuenta;
    private javax.swing.JButton jbMovimientos;
    private javax.swing.JButton jbNotas;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcbActivado;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlCuenta;
    private javax.swing.JLabel jlNotas;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUltimaDepuracion;
    private util.JTextFieldFijo jtffTitulo;
    private util.JTextFieldNumero2Decimales jtfnf2DSaldoActual;
    private util.JTextFieldNumero2Decimales jtfnf2DSaldoUltimaDepuracion;
    private util.JTextFieldNumeroFijo jtfnfCentro;
    private util.JTextFieldNumeroFijo jtfnfCuenta;
    // End of variables declaration//GEN-END:variables
}
