/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package consultas;

import general.DatosComunes;
import java.awt.Component;
import java.awt.Container;
import java.awt.FocusTraversalPolicy;
import java.util.Vector;
import tablas.Cuenta;
import util.Apariencia;

/**
 *
 * @author Txus
 */
public class ConsultaCuentas extends util.EscapeDialog {

    private Cuenta cuenta;
    /**
     * Creates new form ConsultaCuentas
     */
    public ConsultaCuentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargaInicial();
        
        Vector<Component> order;
        order = new Vector<>(2);
        order.add(jtfnfCuenta);       
        MyOFocusTraversalPolicy newPolicy = new MyOFocusTraversalPolicy(order);
        this.setFocusTraversalPolicy(newPolicy);
        
        jtffTitulo.setEditable(false);
        jcbActivado.setEnabled(false);
        jtfnfCentro.setEditable(false);
        jtfnf2DSaldoActual.setEditable(false);
        jtfnf2DSaldoUltimaDepuracion.setEditable(false);      
        
        
        this.setVisible(true);
    }

    private void borrarPantalla(){
        jtfnfCuenta.setText("0");
        jtffTitulo.setText("");
        jtfnfCentro.setText(String.valueOf(DatosComunes.centroCont));
        jcbActivado.setSelected(true);
        jtfnf2DSaldoActual.setText("0,0");
        jtfnf2DSaldoUltimaDepuracion.setText("0,0");
    }
    
    private void cargaInicial(){
        borrarPantalla();
        
        cuenta = new Cuenta();
        
        String strSql = "SELECT * FROM CONTAB WHERE EMPRESA = '" + DatosComunes.eEmpresa + "' AND "
                      + "CONTAB_CENTRO = " + DatosComunes.centroCont + " "
                      + "ORDER BY CONTAB_CUENTA ASC, CONTAB_GRADO ASC LIMIT 1";
        
        cuenta.read(strSql);
        
        cargaDatos(cuenta);
        
        // Comprobamos si tiene las cuentas superiores para no permitir crear 
        // una cuenta de grado inferior sin cuentas superiores.
        if(Integer.valueOf(cuenta.getGrado()) > 1)
            if(cuenta.existenCuentasSuperiores(cuenta.getCuenta()) == false)
                Apariencia.mensajeInformativo(4, "<center>Faltan cuentas superiores!!!<br>Crear cuentas supeirores primero!!!</center>");
    }
    
    private void cargaDatos(Cuenta c){
        jtfnfCuenta.setText(c.getCuenta());
        jtffTitulo.setText(c.getTitulo());
        jtfnfCentro.setText(String.valueOf(c.getCentro()));
        if(c.getActivo() == 1)
            jcbActivado.setSelected(true);
        else
            jcbActivado.setSelected(false);
        jtfnf2DSaldoActual.setText(String.valueOf(c.getSaldo()));
        jtfnf2DSaldoUltimaDepuracion.setText(String.valueOf(c.getSaldoUltimaDepuracion()));        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlCuenta = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbBuscarCuenta = new javax.swing.JButton();
        jtfnfCuenta = new util.JTextFieldNumeroFijo(9);
        jtffTitulo = new util.JTextFieldFijo(30);
        jcbActivado = new javax.swing.JCheckBox();
        jlCentro = new javax.swing.JLabel();
        jtfnfCentro = new util.JTextFieldNumeroFijo(3);
        jbNotas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jlNotas = new javax.swing.JLabel();
        jlUltimaDepuracion = new javax.swing.JLabel();
        jtfnf2DSaldoActual = new util.JTextFieldNumero2Decimales();
        jtfnf2DSaldoUltimaDepuracion = new util.JTextFieldNumero2Decimales();
        jbSalir = new javax.swing.JButton();
        jbAcumuladoContable = new javax.swing.JButton();
        jbMovimientos = new javax.swing.JButton();
        jbPrevisionesPago = new javax.swing.JButton();
        jbAtras = new javax.swing.JButton();
        jbAdelante = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Cuentas");

        jlCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCuenta.setText("Cuenta");

        jlTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlTitulo.setText("Título");

        jbBuscarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BUSCAR.gif"))); // NOI18N
        jbBuscarCuenta.setPreferredSize(new java.awt.Dimension(30, 30));

        jtfnfCuenta.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtffTitulo.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jcbActivado.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jcbActivado.setText("Activado");

        jlCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlCentro.setText("Centro");

        jtfnfCentro.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jbNotas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbNotas.setText("Notas");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Saldos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MS Reference Sans Serif", 1, 14), new java.awt.Color(102, 102, 255))); // NOI18N

        jlNotas.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlNotas.setText("Actual");

        jlUltimaDepuracion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jlUltimaDepuracion.setText("Ultima Depuración");

        jtfnf2DSaldoActual.setText("jTextFieldNumero2Decimales1");
        jtfnf2DSaldoActual.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        jtfnf2DSaldoUltimaDepuracion.setText("jTextFieldNumero2Decimales2");
        jtfnf2DSaldoUltimaDepuracion.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlUltimaDepuracion)
                    .addComponent(jlNotas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfnf2DSaldoActual, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                    .addComponent(jtfnf2DSaldoUltimaDepuracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNotas)
                    .addComponent(jtfnf2DSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUltimaDepuracion)
                    .addComponent(jtfnf2DSaldoUltimaDepuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SALIR.gif"))); // NOI18N
        jbSalir.setPreferredSize(new java.awt.Dimension(30, 30));

        jbAcumuladoContable.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbAcumuladoContable.setText("Acumulado Contable");

        jbMovimientos.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbMovimientos.setText("Movimientos");

        jbPrevisionesPago.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jbPrevisionesPago.setText("Prev.Pago");

        jbAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.gif"))); // NOI18N
        jbAtras.setPreferredSize(new java.awt.Dimension(30, 30));

        jbAdelante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Adelante.gif"))); // NOI18N
        jbAdelante.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTitulo)
                            .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jbAcumuladoContable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbMovimientos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPrevisionesPago))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtffTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(jbNotas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtfnfCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jcbActivado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlCentro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlCuenta)
                            .addComponent(jbBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfnfCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbActivado)
                            .addComponent(jlCentro)
                            .addComponent(jtfnfCentro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlTitulo)
                            .addComponent(jtffTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbNotas)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAcumuladoContable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPrevisionesPago, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAdelante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   

    public static class MyOFocusTraversalPolicy
            extends FocusTraversalPolicy {
 
        Vector<Component> order;
 
        public MyOFocusTraversalPolicy(Vector<Component> order) {
            this.order = new Vector<Component>(order.size());
            this.order.addAll(order);
        }
 
        public Component getComponentAfter(Container focusCycleRoot,
                Component aComponent) {
            int idx = (order.indexOf(aComponent) + 1) % order.size();
            return order.get(idx);
        }
 
        public Component getComponentBefore(Container focusCycleRoot,
                Component aComponent) {
            int idx = order.indexOf(aComponent) - 1;
            if (idx < 0) {
                idx = order.size() - 1;
            }
            return order.get(idx);
        }
 
        public Component getDefaultComponent(Container focusCycleRoot) {
            return order.get(0);
        }
 
        public Component getLastComponent(Container focusCycleRoot) {
            return order.lastElement();
        }
 
        public Component getFirstComponent(Container focusCycleRoot) {
            return order.get(0);
        }
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAcumuladoContable;
    private javax.swing.JButton jbAdelante;
    private javax.swing.JButton jbAtras;
    private javax.swing.JButton jbBuscarCuenta;
    private javax.swing.JButton jbMovimientos;
    private javax.swing.JButton jbNotas;
    private javax.swing.JButton jbPrevisionesPago;
    private javax.swing.JButton jbSalir;
    private javax.swing.JCheckBox jcbActivado;
    private javax.swing.JLabel jlCentro;
    private javax.swing.JLabel jlCuenta;
    private javax.swing.JLabel jlNotas;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlUltimaDepuracion;
    private util.JTextFieldFijo jtffTitulo;
    private util.JTextFieldNumero2Decimales jtfnf2DSaldoActual;
    private util.JTextFieldNumero2Decimales jtfnf2DSaldoUltimaDepuracion;
    private util.JTextFieldNumeroFijo jtfnfCentro;
    private util.JTextFieldNumeroFijo jtfnfCuenta;
    // End of variables declaration//GEN-END:variables
}
